### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by shlok2740** [JimmyCHL/discord-blockchain-gun-heroku-clone-03-01-22#1]
How to deploy it man

**Comment by JimmyCHL** [comment]
@shlok2740 hey, what do you mean how to deploy?? You wanna deploy to vercel or?

**Comment by shlok2740** [comment]
I want to deploy it but the server doesnt work there when i deployed the client at vercel

**Comment by JimmyCHL** [comment]
do you can deploy client to vercel, but you are not able to deploy your server to heroku?  You need to deployed your server in heroku. And you can connect that address to your Gun inside your client for peer and peer connection.

**Comment by JimmyCHL** [comment]
i have my tiptoSever folder i put that in the client folder. Please check that and deploy your express server on heroku.

**Comment by shlok2740** [comment]
Man i didnt have my tiptoServer folder, but now i have deployed it. Thanks man
